services:
  productpage:
    image: ${REPO}/examples-bookinfo-productpage-v1:${TAG}
    networks:
      - bookinfo-network
    healthcheck:
      test: [ "CMD", "curl", "-H", "-f", "http://localhost:9080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    logging: &logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
    environment:
      OTEL_SERVICE_NAME: "productpage"
      OTEL_RESOURCE_ATTRIBUTES: "service.namespace=bookinfo"
      OTEL_TRACES_EXPORTER: "console,otlp"
      OTEL_METRICS_EXPORTER: "console,otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${COLLECTOR_ENDPOINT}:4317 
      OTEL_LOG_LEVEL: DEBUG
    ports:
      - "9080:9080"
  mysqldb:
    image: ${REPO}/examples-bookinfo-mysqldb:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - ./src/mysql/mysql_data:/var/lib/mysql
    networks:
      - bookinfo-network
    environment:
      MYSQL_ROOT_PASSWORD: password
    logging:
      <<: *logging
  ratings:
    image: ${REPO}/examples-bookinfo-ratings-v2:${TAG}
    environment:
      SERVICE_VERSION: v2
      DB_TYPE: mysql
      MYSQL_DB_HOST: mysqldb
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: password
      HOST_IP: 172.19.0.1
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "${COLLECTOR_ENDPOINT}:4318" 
      OTEL_NODE_RESOURCE_DETECTORS: "env,host,os"
      OTEL_RESOURCE_ATTRIBUTES: "service.namespace=bookinfo"
      OTEL_SERVICE_NAME: "ratings"
      NODE_OPTIONS: "--require @opentelemetry/auto-instrumentations-node/register"
    depends_on:
      - mysqldb
    networks:
      - bookinfo-network
    healthcheck:
      test: [ "CMD", "curl", "-H", "-f", "http://localhost:9080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging
  reviews:
    image: ${REPO}/examples-bookinfo-reviews-v3:${TAG}
    # needs javaagent.jar copied into /opt/ibm/wlp/usr/shared/apps
    # options in jvm.options into /opt/ibm/wlp/usr/servers/defaultServer/
    # OTel stuff is in src/reviews/otel
    networks:
      - bookinfo-network
    volumes:
      - /Users/Rainer/GitHub/training-bookinfo/src/reviews/otel/jvm.options:/opt/ibm/wlp/usr/servers/defaultServer/jvm.options
      - /Users/Rainer/GitHub/training-bookinfo/src/reviews/otel/opentelemetry-javaagent.jar:/opt/ibm/wlp/usr/shared/apps/opentelemetry-javaagent.jar
    healthcheck:
      test: [ "CMD", "curl", "-H", "-f", "http://localhost:9080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging
    environment:
      OTEL_RESOURCE_ATTRIBUTES: "service.namespace=bookinfo"
      OTEL_SERVICE_NAME: "reviews"
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: "${COLLECTOR_ENDPOINT}:4318" 
    extra_hosts:
      - "host.docker.internal:172.31.0.1"
  details:
    image: ${REPO}/examples-bookinfo-details-v1:${TAG}
    networks:
      - bookinfo-network
    healthcheck:
      test: [ "CMD", "curl", "-H", "-f", "http://localhost:9080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: "${COLLECTOR_ENDPOINT}:4318" 
      OTEL_RESOURCE_ATTRIBUTES: "service.namespace=bookinfo"
    logging:
      <<: *logging

networks:
  bookinfo-network:
